### ISSUE TITLE
We need a chat

### ISSUE THREAD

**Issue by ryanhcode** [partlybakedideas/UniTracker#1]
Chat here

**Comment by partlybakedideas** [comment]
I found `pug.js` weird so I am converting it to html.

**Comment by partlybakedideas** [comment]
I made the html stub already.

**Comment by marcusparsons** [comment]
I made a Discord channel for everyone to use: https://discord.gg/nmj9bX

**Comment by partlybakedideas** [comment]
> I made a Discord channel for everyone to use: https://discord.gg/nmj9bX
This is fine, @marcusparsons. Plus, I don't have a discord account.

**Comment by partlybakedideas** [comment]
Pardon me, but I don't know how to use `express` or `pug.js`. are there any good courses for those two?

**Comment by ryanhcode** [comment]
@partlybakedideas
Look on the docs and YouTube. Pug is the one that would help a lot for you to know.

**Comment by ryanhcode** [comment]
@partlybakedideas there is also an html to pug translator

**Comment by marcusparsons** [comment]
Discord is extremely easy to use, and a lot of people use it.  It's an excellent service.  Just sign up for an account and then click the invite link.  There are tons of people that use it for various things.

**Comment by ryanhcode** [comment]
@marcusparsons I might be wrong but I think he doesn’t have an account because he would be breaking the TOS if he did

**Comment by marcusparsons** [comment]
How so?

**Comment by ryanhcode** [comment]
Well they have age limits and stuff.

**Comment by marcusparsons** [comment]
They're only stipulation is that you are 13 years of age or older...are you telling me that he is under 13?

**Comment by ryanhcode** [comment]
No. I’m not just going to make random assumptions about people.

**Comment by marcusparsons** [comment]
You are the one who said he would be violating the TOS of Discord because of age restrictions, Ryan, not I.  I had to naturally assume that you knew he was underage because you directly said he would be violating TOS if he signed up for Discord, which is just a chat server.

**Comment by ryanhcode** [comment]
I did not intent to offend anyone. I am sorry for any commotion.

**Comment by marcusparsons** [comment]
Listen, I made a chat channel that everyone can join, because commenting in threads like this doesn't help anyone. You need a live way to chat.  Discord is a great platform for that. Period.

**Comment by partlybakedideas** [comment]
It's fine, @ryanhcode.

**Comment by ryanhcode** [comment]
Arghhhh why is the value of this text box returning null.......

**Comment by marcusparsons** [comment]
Are you all going to join the Discord chat? If not, I don't see any point in continuing this thread.

**Comment by ryanhcode** [comment]
@marcusparsons I think this thread is the chat

**Comment by marcusparsons** [comment]
This is not a chat.  Guys, this isn't how you operate in a team. You don't blow up an issue on GitHub.  You chat in A CHAT SERVER LIKE DISCORD.  It's not that difficult to comprehend.

**Comment by marcusparsons** [comment]
I have never been a part of such a frustrating experience as just trying to get you all to get into the Discord server so we can actually chat/talk in real time.  You can even screen share from Discord which makes it handy for diagnosing issues. You're being an idiot by not utilizing the power of a well known platform.

**Comment by ryanhcode** [comment]
You don’t have to help us if you don’t want to. If he doesn’t want to use Discord, we don’t have to.

**Comment by partlybakedideas** [comment]
And again, terms of service...

**Comment by ryanhcode** [comment]
Okay! The discord server was deleted. We can chat here, or, if you have something relating to the app please email me at ryan_hallihan@outlook.com

**Comment by marcusparsons** [comment]
Please remove me from this repository as a contributor. Thanks. Good luck.

**Comment by partlybakedideas** [comment]
Well, I am going to close this issue and make a new one.
